apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas.yaml
    target:
      kind: Deployment
      name: video-rsrv
  - path: strategy.yaml
    target:
      kind: Deployment
      name: video-rsrv
  - path: ingress.yaml
    target:
      kind: Ingress
      name: video-rsrv-ingress
