apiVersion: v1
kind: Service
metadata:
  namespace: dataprovider
  name: video-rsrv-svc
  labels:
    app: video-rsrv-app
spec:
  type: NodePort
  ports:
    - port: 9090
      name: http
      protocol: TCP
      targetPort: http
  selector:
    app: video-rsrv-app
